
/* 53806.51 */ BEGIN TRANSACTION
/* Obtener MAX IDMAEDPCD */ 
SELECT COALESCE(MAX(IDMAEDPCD),1) AS MAXNUDO FROM MAEDPCD WITH ( NOLOCK ) 

/* Obtener MAX IDMAEDPCE (custom string)*/ 
SELECT TOP 1 IDMAEDPCE,SUBSTRING(NUDP,3,8) AS MAXNUDO FROM MAEDPCE WITH ( NOLOCK ) WHERE EMPRESA='01' AND TIDP='TJV' AND ISNUMERIC(SUBSTRING(NUDP,3,8))>0 ORDER BY SUBSTRING(NUDP,3,8) DESC

/* Obtener max MAEDPCE (probablemente para asegurar escritura anterior) */ 
SELECT TOP 1 * FROM MAEDPCE WITH ( NOLOCK ) WHERE EMPRESA='01' AND TIDP='TJV' AND NUDP='0100000006' AND ENDP='05643210 '

/* BUSCAR SI USUSARIO TIENE PERMISO */ SELECT TOP 1 * FROM MAEUS WITH ( NOLOCK ) WHERE KOUS='RAM' AND KOOP='NO000080'

/* GRabar encabezado de documento de pago */ 
INSERT INTO MAEDPCE 
( EMPRESA,TIDP,NUDP,ENDP,NUCUDP,CUDP,EMDP,SUEMDP,FEEMDP,FEVEDP,MODP,TIMODP,TAMODP,REFANTI,SUREDP,CJREDP,KOTU,KOFUDP,KOTNDP,SUTNDP,TUVOPROTES,VADP,VAASDP,VAVUDP,ESASDP,VAABDP,ESPGDP,CUOTAS,HORAGRAB,LAHORA,ARCHIRSD,IDRSD,REFERENCIA) 
VALUES ( '01','TJV','0100000006','05643210 ','doc 1 ','cuenta 1 ','901 ',' ',{d '2017-11-13'},{d '2017-11-13'},'$ ','N',700.02000,'ref ant ','001','01','1','RAM','96544490-4 ','01',0,99.00000,55.00000,14.00000,'P',0.0,'P',1.00000,53806,{d '2017-11-13'},' ',0.00000,1294.000000)
/* Obtener último ID de MAEDPCE para usar en grabación de asignaciónes */
SELECT @@IDENTITY AS ULTID

/* Obtener datos del documento a pagar */
SELECT TOP 1 IDMAEEDO,EMPRESA,ENDO,TIDO,NUDO,VAPIDO,VAABDO,TIMODO,BLOQUEAPAG FROM MAEEDO WITH ( NOLOCK ) WHERE IDMAEEDO=1192
/* Actualizar campo VAABDO de cada MAEEDO asignado */
UPDATE MAEEDO SET VAABDO= COALESCE(VAABDO,0) +22.00000 WHERE IDMAEEDO=1192
/* Recalcular el estado ESPGDO de cada MAEEDO (C si la deuda menor igual que cero)*/
UPDATE MAEEDO SET ESPGDO=CASE WHEN ROUND(VABRDO,2)-ROUND(VAABDO,2)-COALESCE(ROUND(VAIVARET,2),0) <= 0 THEN 'C' ELSE ESPGDO END WHERE IDMAEEDO=1192
/* Traer datos MAEVEN documento MAEEDO */
SELECT VAVE,VAABVE,IDMAEVEN FROM MAEVEN WITH ( NOLOCK ) WHERE IDMAEEDO=1192 AND ESPGVE<>'C' 
/* Actualizar MAEVEN con el DMAEVEN relacionado al EDO*/ 
UPDATE MAEVEN SET VAABVE= COALESCE(VAABVE,0.0)+22.00000 WHERE IDMAEVEN=389
/* Recalcular el estado ESPGDO de cada documento en la MAEVEN (C si la deuda menor igual que cero)*/
UPDATE MAEVEN SET ESPGVE=CASE WHEN ROUND(VAVE,2)-ROUND(VAABVE,2) <= 0 THEN 'C' ELSE ESPGVE END WHERE IDMAEVEN=389

/* Insertar detalle de pago */
INSERT INTO MAEDPCD ( IDMAEDPCE,VAASDP,FEASDP,IDRST,TIDOPA,ARCHIRST,TCASIG,REFERENCIA,KOFUASDP,SUASDP,CJASDP,HORAGRAB,LAHORA) 
VALUES ( 1234,22.00000,{d '2017-11-13'},1192,'FCV','MAEEDO',700.02000,1294.000000,'RAM','001','01',53807,{d '2017-11-13'})

/* Obtener datos del documento a pagar */ 
SELECT TOP 1 IDMAEEDO,EMPRESA,ENDO,TIDO,NUDO,VAPIDO,VAABDO,TIMODO,BLOQUEAPAG FROM MAEEDO WITH ( NOLOCK ) WHERE IDMAEEDO=1207
/* Actualizar campo VAABDO de cada MAEEDO asignado */
UPDATE MAEEDO SET VAABDO= COALESCE(VAABDO,0) +33.00000 WHERE IDMAEEDO=1207
/* Recalcular el estado ESPGDO de cada MAEEDO (C si la deuda menor igual que cero)*/
 UPDATE MAEEDO SET ESPGDO=CASE WHEN ROUND(VABRDO,2)-ROUND(VAABDO,2)-COALESCE(ROUND(VAIVARET,2),0) <= 0 THEN 'C' ELSE ESPGDO END WHERE IDMAEEDO=1207
/* Traer datos MAEVEN documento MAEEDO */
 SELECT VAVE,VAABVE,IDMAEVEN FROM MAEVEN WITH ( NOLOCK ) WHERE IDMAEEDO=1207 AND ESPGVE<>'C' 
/* Actualizar MAEVEN con el DMAEVEN relacionado al EDO*/ 
 UPDATE MAEVEN SET VAABVE= COALESCE(VAABVE,0.0)+33.00000 WHERE IDMAEVEN=395
/* Recalcular el estado ESPGDO de cada documento en la MAEVEN (C si la deuda menor igual que cero)*/
UPDATE MAEVEN SET ESPGVE=CASE WHEN ROUND(VAVE,2)-ROUND(VAABVE,2) <= 0 THEN 'C' ELSE ESPGVE END WHERE IDMAEVEN=395

/* Insertar detalle de pago */
 INSERT INTO MAEDPCD ( IDMAEDPCE,VAASDP,FEASDP,IDRST,TIDOPA,ARCHIRST,TCASIG,REFERENCIA,KOFUASDP,SUASDP,CJASDP,HORAGRAB,LAHORA) VALUES ( 1234,33.00000,{d '2017-11-13'},1207,'FCV','MAEEDO ',700.02000,1294.000000,'RAM','001','01',53807,{d '2017-11-13'})
 COMMIT TRANSACTION
