-- Traer CEMENTO MELON en VIDRIOSZ

/* traeDeuda */ 
SELECT 
EDO.IDMAEEDO,EDO.EMPRESA, EDO.TIDO, EDO.NUDO, EDO.ENDO, EDO.SUENDO, EDO.MODO, EDO.TIMODO, EDO.TAMODO, EDO.ESPGDO, EDO.FEULVEDO, ROUND(EDO.VABRDO,2) AS VABRDO, ROUND(EDO.VAABDO,2) AS VAABDO,ROUND(EDO.VAIVARET,2) AS VAIVARET, ROUND(EDO.VAIVDO,2) AS VAIVDO, ROUND(EDO.VANEDO,2) AS VANEDO,EDO.BLOQUEAPAG  
FROM MAEEDO AS EDO  WITH ( NOLOCK )  
WHERE 
EDO.ENDO='05643210     ' 
AND EDO.TIDO IN  ('BLV','BSV','BLX','FCV','FDB','FDV','FDX','FDZ','FEV','FVL','FVT','FVX','FXV','FYV','FVZ','RIN','ESC','FEE','FDE','NCC','NCB')  
AND EDO.ESPGDO = 'P'  
AND EDO.NUDONODEFI = 0  
AND EDO.EMPRESA = '01'  
ORDER BY EDO.TIDO,EDO.NUDO 

/* Saldo vencido */ 
SELECT 
SUM((ROUND(VEN.VAVE,2)-ROUND(VEN.VAABVE,2))*(CASE WHEN EDO.TIDO IN  ('NCV','NCX','NCZ','NEV','NCE','NCC','NCB')  THEN -1 ELSE 1 END)) AS SALDOVEN  
FROM 
MAEEDO AS EDO  WITH ( NOLOCK )  
INNER JOIN MAEVEN AS VEN ON VEN.IDMAEEDO=EDO.IDMAEEDO  
AND VEN.FEVE<={d '2017-11-08'} 
AND VEN.ESPGVE=' '  
WHERE 
EDO.ENDO='05643210     '  
AND EDO.TIDO IN  ('BLV','BSV','BLX','FCV','FDB','FDV','FDX','FDZ','FEV','FVL','FVT','FVX','FXV','FYV','FVZ','RIN','ESC','FEE','FDE','NCC','NCB')  
AND EDO.EMPRESA = '01'  
AND EDO.ESPGDO = 'P'  AND EDO.NUDONODEFI = 0 

/* Guía CTE */ 
SELECT 
SUM( CASE  WHEN UDTRPR=1 AND PRCT=0 AND CAPRCO1<>0 AND CAPRCO1-CAPRAD1-CAPREX1>0 THEN (VABRLI*(CAPRCO1-CAPRAD1-CAPREX1))/CAPRCO1  WHEN UDTRPR=1 AND PRCT=0 AND CAPRCO1=0  THEN 0  WHEN UDTRPR=1 AND PRCT=1 AND TICT='D'   AND CAPRCO1-CAPRAD1-CAPREX1>0 THEN (CAPRCO1-CAPRAD1-CAPREX1)*(-1.0)  WHEN UDTRPR=1 AND PRCT=1 AND TICT='R'   AND CAPRCO1-CAPRAD1-CAPREX1>0 THEN (CAPRCO1-CAPRAD1-CAPREX1)  WHEN UDTRPR=2 AND PRCT=0 AND CAPRCO2<>0 AND CAPRCO2-CAPRAD2-CAPREX2>0 THEN (VABRLI*(CAPRCO2-CAPRAD2-CAPREX2))/CAPRCO2  WHEN UDTRPR=2 AND PRCT=0 AND CAPRCO2=0  THEN 0  WHEN UDTRPR=2 AND PRCT=1 AND TICT='D'   AND CAPRCO2-CAPRAD2-CAPREX2>0 THEN (CAPRCO2-CAPRAD2-CAPREX2)*(-1.0)  WHEN UDTRPR=2 AND PRCT=1 AND TICT='R'   AND CAPRCO2-CAPRAD2-CAPREX2>0 THEN (CAPRCO2-CAPRAD2-CAPREX2)  ELSE 0 END * CASE WHEN TIDO='GRD' THEN -1 ELSE 1 END  ) AS GUIACTE  FROM MAEEDO WITH ( NOLOCK )  INNER JOIN ( SELECT IDMAEEDO,UDTRPR,PRCT,TICT,CAPRCO1,CAPRAD1,CAPREX1,CAPRCO2,CAPRAD2,CAPREX2,VABRLI  
FROM 
MAEDDO WITH ( NOLOCK )  
WHERE ENDO='05643210     '  
AND TIDO IN ('GDV','GRD')   
AND ESLIDO=' '  
AND LILG IN ('SI','GR') ) AS MAEDDO ON MAEEDO.IDMAEEDO=MAEDDO.IDMAEEDO  
WHERE 
MAEEDO.ENDO = '05643210     '  
AND MAEEDO.TIDO IN ('GDV','GRD')  
AND EMPRESA='01' 


/* DOCCOE?? */ 
SELECT 
EDO.IDDOCCOE,EDO.EMPRESA,EDO.TIDO, EDO.NUDO, EDO.ENDO, EDO.SUENDO, EDO.MODO, EDO.TIMODO, EDO.TAMODO, EDO.ESPGDO, ROUND(EDO.VABRDO,2) AS VABRDO, ROUND(EDO.VAABDO,2) AS VAABDO, EDO.FEVEDO  
FROM 
CDOCCOE AS EDO  WITH ( NOLOCK )  
INNER JOIN CFORMCON ON CFORMCON.KOFORMU=EDO.TIDO AND CFORMCON.VAABDO > 0 AND CFORMCON.ARCHIENDO='MAEEN   '  
WHERE 
EDO.ENDO='05643210     ' 
AND EDO.ESPGDO = 'P'  
AND EDO.SIMILSISTE ='V'  
AND EDO.EMPRESA = '01' 

/* Pagos */ 
SELECT 
DPCE.IDMAEDPCE,DPCE.EMPRESA,DPCE.TIDP, DPCE.NUDP, DPCE.ENDP, DPCE.EMDP, DPCE.SUEMDP, DPCE.CUDP,DPCE.NUCUDP, DPCE.FEEMDP, DPCE.FEVEDP, DPCE.MODP, DPCE.TIMODP, DPCE.TAMODP,DPCE.VADP, DPCE.VAABDP, DPCE.VAASDP, DPCE.VAVUDP, DPCE.ESPGDP, DPCE.REFANTI , DPCE.ARCHIRSD , DPCE.IDRSD  
FROM 
MAEDPCE AS DPCE  WITH ( NOLOCK )  
WHERE 
DPCE.ENDP = '05643210     ' 
AND DPCE.TIDP IN  ('ATB','CHV','CPV','CRV','DEP','EFV','LTV','PAV','RBV','RGV','RIV','TJV','VUE')  
AND DPCE.ESASDP = 'P'  
AND DPCE.ESPGDP<> 'N'  
AND DPCE.EMPRESA = '01' 

/* Documentos de pago como deuda */ 
SELECT 
DPCE.IDMAEDPCE,DPCE.EMPRESA,DPCE.TIDP, DPCE.NUDP, DPCE.ENDP, DPCE.EMDP, DPCE.SUEMDP, DPCE.CUDP,       DPCE.NUCUDP, DPCE.FEEMDP, DPCE.FEVEDP, DPCE.MODP, DPCE.TIMODP, DPCE.TAMODP,       DPCE.VADP, DPCE.VAABDP, DPCE.VAASDP, DPCE.VAVUDP, DPCE.ESPGDP, DPCE.REFANTI  FROM MAEDPCE AS DPCE  WITH ( NOLOCK )  WHERE DPCE.ENDP = '05643210     '  AND DPCE.TIDP IN  ('ATB','CHV','CPV','CRV','DEP','EFV','LTV','PAV','RBV','RGV','RIV','TJV','VUE')  AND ( DPCE.ESPGDP = 'P' OR DPCE.ESPGDP = 'R' )  AND DPCE.EMPRESA = '01' 
