'use strict';

module.exports = {
    templateEngine: 'swig',
    sessionSecret: 'MEAN',
    sessionCollection: 'sessions',
    assets: {
        lib: {
            css: [
                "public/ng_modules/bootstrap/dist/css/bootstrap.css",
                "public/ng_modules/datatables/media/css/jquery.dataTables.css",
                "public/ng_modules/font-awesome/css/font-awesome.min.css",
                "public/ng_modules/angular-material/angular-material.css",
                "public/ng_modules/angular-toastr/dist/angular-toastr.css",
                "public/ng_modules/angular-ui-select/dist/select.css",
                "public/ng_modules/angular-ui-grid/ui-grid.min.css",
                "public/ng_modules/animate.css/animate.css",
                "public/ng_modules/bootstrap-daterangepicker/daterangepicker-bs3.css",
                "public/ng_modules/morrisjs/morris.css",
                "public/ng_modules/ng-tags-input/ng-tags-input.min.css",
                "public/ng_modules/ng-tags-input/ng-tags-input.bootstrap.min.css",
                "public/modules/theme/styles/main.css", 
                'public/ng_modules/handsontable/dist/handsontable.full.css',
                'public/ng_modules/froala-wysiwyg-editor/css/froala_editor.min.css',
                'public/ng_modules/froala-wysiwyg-editor/css/plugins/code_view.min.css',
                'public/ng_modules/froala-wysiwyg-editor/css/plugins/table.min.css'             
                //"public/ng_modules/jsoneditor/dist/jsoneditor.min.css"
            ],
            js: [
                'public/ng_modules/api-check/dist/api-check.js',
                'public/ng_modules/Chart.js/Chart.js',
                "public/ng_modules/jquery/dist/jquery.js",
                "public/ng_modules/angular/angular.js",
                "public/ng_modules/angular-animate/angular-animate.js",
                //"public/ng_modules/angular-i18n/angular-locale_es_cl.js",
                "public/ng_modules/angular-bootstrap/ui-bootstrap-tpls.js",
                'public/ng_modules/froala-wysiwyg-editor/js/froala_editor.min.js',
                'public/ng_modules/froala-wysiwyg-editor/js/plugins/code_view.min.js',
                'public/ng_modules/froala-wysiwyg-editor/js/plugins/table.min.js',
                'public/ng_modules/froala-wysiwyg-editor/js/plugins/code_beautifier.min.js',
                "public/ng_modules/bootstrap/dist/js/bootstrap.min.js",
                "public/ng_modules/angular-cookies/angular-cookies.js",               
                //"public/ng_modules/jsoneditor/dist/jsoneditor.min.js",
                //"public/ng_modules/ng-jsoneditor/ng-jsoneditor.min.js",               
                'public/ng_modules/datatables/media/js/jquery.dataTables.min.js',
                'public/ng_modules/angular-datatables/dist/angular-datatables.min.js',
                'public/ng_modules/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.min.js',
                //'public/ng_modules/angular-datatables/dist/plugins/buttons/angular-datatables.buttons.min.js',
                "public/ng_modules/angular-datatables/dist/plugins/columnfilter/angular-datatables.columnfilter.min.js",
                //"public/ng_modules/angular-datatables/dist/plugins/colreorder/angular-datatables.colreorder.min.js",
                //"public/ng_modules/angular-datatables/dist/plugins/fixedheader/angular-datatables.fixedheader.min.js",
                "public/ng_modules/angular-datatables/dist/plugins/scroller/angular-datatables.scroller.min.js",
                //"public/ng_modules/angular-datatables/dist/plugins/tabletools/angular-datatables.tabletools.min.js",
                "public/ng_modules/d3/d3.js",
                "public/ng_modules/angular-fontawesome/dist/angular-fontawesome.js",
                "public/ng_modules/angular-fullscreen/src/angular-fullscreen.js",
                "public/ng_modules/angular-simple-logger/dist/angular-simple-logger.js",
                //"public/ng_modules/lodash/lodash.js",
                "public/ng_modules/angular-loading-bar/build/loading-bar.js",
                "public/ng_modules/eventEmitter/EventEmitter.js",
                //"public/ng_modules/imagesloaded/imagesloaded.js",
                "public/ng_modules/angular-aria/angular-aria.js",
                "public/ng_modules/angular-material/angular-material.js",
                //"public/ng_modules/angular-messages/angular-messages.js",
                "public/ng_modules/moment/moment.js",
                "public/ng_modules/angular-momentjs/angular-momentjs.js",
                "public/ng_modules/angular-resource/angular-resource.js",
                "public/ng_modules/angular-sanitize/angular-sanitize.js",
                "public/ng_modules/angular-toastr/dist/angular-toastr.tpls.js",
                "public/ng_modules/angular-touch/angular-touch.js",
                "public/ng_modules/angular-translate/angular-translate.js",
                "public/ng_modules/angular-translate-loader-static-files/angular-translate-loader-static-files.js",
                "public/ng_modules/angular-translate-storage-cookie/angular-translate-storage-cookie.js",
                "public/ng_modules/angular-translate-storage-local/angular-translate-storage-local.js",
                "public/ng_modules/jquery-ui/ui/jquery-ui.js",
                "public/ng_modules/angular-ui-router/release/angular-ui-router.js",
                "public/ng_modules/angular-ui-select/dist/select.js",
                //"public/ng_modules/angular-ui-tree/dist/angular-ui-tree.js",
                "public/ng_modules/angular-ui-utils/ui-utils.js",
                //"public/ng_modules/angular-ui-grid/ui-grid.js",
                "public/ng_modules/bootstrap-daterangepicker/daterangepicker.js",
                "public/ng_modules/ng-bs-daterangepicker/src/ng-bs-daterangepicker.js",
                //"public/ng_modules/jquery.easy-pie-chart/dist/angular.easypiechart.min.js",
                "public/ng_modules/raphael/raphael.js",
                "public/ng_modules/morrisjs/morris.js",
                "public/ng_modules/ng-tags-input/ng-tags-input.min.js",
                "public/ng_modules/oclazyload/dist/ocLazyLoad.js",
                'public/ng_modules/angular-chart.js/dist/angular-chart.js',            
                'public/ng_modules/angular-breadcrumb/dist/angular-breadcrumb.min.js',            
                'public/ng_modules/handsontable/dist/handsontable.full.js',
                'public/ng_modules/ngHandsontable/dist/ngHandsontable.js',
                'public/ng_modules/angular-smart-table/dist/smart-table.js',
                'public/ng_modules/clipboard/dist/clipboard.min.js',
                'public/ng_modules/ngclipboard/dist/ngclipboard.min.js'
            ]
        },
        css: [
            'public/modules/core/css/*.css'
        ],
        js: [
            'public/config.js',
            'public/application.js',
            'public/modules/*/*.js',
            'public/modules/**/*.js'
        ],
        tests: [

        ]
    }
};